Zeit am Ende des Artikels verbessern.
chaos-jetzt/ds_artikel_2020 pull request #6
Opened 2020-03-04 09:11 UTC by e1mo

Close #5

2020-03-04 09:12 UTC, e1mo commented on chaosjetzt.tex
> -Dort sollen sich nochmals speziell Jugendliche treffen und Diskussionen sowie kleinere Workshops miteinander gestalten können.
Hier ist mir noch unklar wie wir diesen Satz mit rein bringen wollen. Etwas über die Inhalte berichten wäre schon gut imo

2020-03-04 10:31 UTC, rugk requested changes

2020-03-04 10:31 UTC, rugk commented on chaosjetzt.tex
> +Das erste Geekend wurde bereits auf dem 36c3 erfolgreich geplant und fand ende Februar 2020 im Göttinger Neotopia statt. Das größtenteils durch den CCC finanzierte Wochenende war mit knapp 30 Besuche
```suggestion
Das erste Geekend wurde bereits auf dem 36c3 erfolgreich geplant und fand Ende Februar 2020 im Göttinger Neotopia statt. Das größtenteils durch den CCC finanzierte Wochenende war mit knapp 30 Besuchenden ausgebucht und bot eine gute Atmosphäre für ein effektives Findungstreffen.
```

2020-03-04 10:31 UTC, rugk commented on chaosjetzt.tex
```suggestion
In verschiedenen, ad-hoc gegründeten Arbeitsgruppen wurden Themen wie die Social-Media-Präsenz oder die Möglichkeiten und Ziele zur \enquote{Verjüngung} der Hackspaces diskutiert.
```

(evt. "bearbeitet" statt "diskutiert" am Ende)

2020-03-04 10:32 UTC, rugk commented on chaosjetzt.tex
> -Dort sollen sich nochmals speziell Jugendliche treffen und Diskussionen sowie kleinere Workshops miteinander gestalten können.
Vorschlag unter https://github.com/chaos-jetzt/ds_artikel_2020/pull/6#discussion_r387578039

2020-03-06 16:37 UTC, rugk approved these changes

2020-03-06 18:27 UTC, closed without merging

2020-03-06 20:56 UTC, rugk commented
Why? :cry:

2020-03-06 20:57 UTC, rugk commented
Ah okay, wurde ersetzt durch https://github.com/chaos-jetzt/ds_artikel_2020/commit/cd77a4f607756957ca44c969247a2a55cd0e6016

2020-03-06 20:58 UTC, rugk commented
Irgendwie ist der Merge auf GitHub kaputt gegangen, aber in https://github.com/chaos-jetzt/ds_artikel_2020/commit/e3f526f7f35658ac79ade077580aec4a7da7a8d1 gemerged offenbar. Komisch… :thinking: Egal.

2020-03-06 21:13 UTC, e1mo commented
Ja, ich habe des Signings Wegen über die CLI gemerged, und Github hat das irgendwie nicht gematched. Und nur damit der PR sauber geschlossen ist wollte ich nicht zwei mal mergen