Absatz zum Geekend ergänzt und Formulierungen hübsch gemacht
chaos-jetzt/ds_artikel_2020 pull request #9
Opened 2020-03-09 21:30 UTC by raketenlurch

2020-03-09 22:05 UTC, e1mo requested changes
sieht alles in allem gut aus!

Noch ein paar kleinere Änderungen mit etwas unschönen Formulierungen.

2020-03-09 22:05 UTC, e1mo commented on chaosjetzt.tex
> +jungen Leuten zu überlegen, welche Strukturen sie sich wünschen.
```suggestion
jungen Leuten zu überlegen, welche Strukturen wir uns wünschen.
```

2020-03-09 22:05 UTC, e1mo commented on chaosjetzt.tex
> +in kleineren und größeren Gruppen über verschiedene Themen gesprochen. Da es das erste Treffen war ging es inhaltlich mehr um Meta-Themen,
```suggestion
uns in kleineren und größeren Gruppen über verschiedene Themen ausgetauscht. Da es das erste Treffen war ging es inhaltlich mehr um Meta-Themen,
```

2020-03-09 22:05 UTC, e1mo commented on chaosjetzt.tex
> +wollen wir benutzen?". In längeren Plena, die dank Vereinbarungen, wie "Tooldiskussionen nicht im großem Plenum" trotzdem erstaunlich
ist das "Tooldiskussionen nicht im großem Plenum" vielleicht etwas zu viel Information?

2020-03-09 22:05 UTC, e1mo commented on chaosjetzt.tex
> +kurzweilig geblieben sind, sind wir zu ersten Ergebnissen gekommen, die eine gute Grundlage für weitere Diskussionen bieten. Im Laufe des
```suggestion
kurzweilig blieben, kamen wir zu ersten Ergebnissen. Dies bot eine gute Grundlage für weitere Diskussionen. Im Laufe des
```

2020-03-09 22:05 UTC, e1mo commented on chaosjetzt.tex
> +(hauptsächlich Einhörner und Blahajs) nicht zu kurz gekommen. Am Ende war es so schön, dass zur Abmilderung der allseits bekannten
```suggestion
(hauptsächlich Einhörner und Blåhajs) nicht zu kurz gekommen. Am Ende war es so schön, dass zur Abmilderung der allseits bekannten
```

2020-03-10 11:19 UTC, raketenlurch commented
Done. Änderungen sind drin.

2020-03-10 14:16 UTC, e1mo approved these changes
Sieht gut aus für mich. Wenn kein Mensch da noch etwas hat würde ich das gegen 19:00 mergen.

2020-03-10 16:05 UTC, rugk requested changes

2020-03-10 16:05 UTC, rugk commented on chaosjetzt.tex
> +Wochenendes wurde "Wir wollen kaputte Strukturen im CCC reparieren - mit und ohne Lötkolben" zum neuen, inoffiziellen Motto. Neben der
```suggestion
wie zum Beispiel \enquote{Wie wollen wir Entscheidungen treffen und Menschen mandatieren?}, \enquote{Was wollen wir inhaltlich machen?} und \enquote{Welche Tools 
wollen wir benutzen?}. In längeren Plena, die erstaunlich kurzweilig blieben, kamen wir zu ersten Ergebnissen. Dies bot eine gute Grundlage für weitere Diskussionen. Im Laufe des
Wochenendes wurde \enquote{Wir wollen kaputte Strukturen im CCC reparieren - mit und ohne Lötkolben} zum neuen, inoffiziellen Motto. Neben der 
```

This is tex, so use good styled quotation marks :smile:

2020-03-10 16:05 UTC, rugk commented on chaosjetzt.tex
> +Auf dem 36c3 sind wir dann als Gruppe das erste Mal auf einer Veranstltung aufgetreten. Wir organisierten in der \emph{WikipakaWG} zusammen mit Jugend~hackt eine Assembly mit eigenem Dome.
```suggestion
Auf dem 36c3 sind wir dann als Gruppe das erste Mal auf einer Veranstaltung aufgetreten. Wir organisierten in der \emph{WikipakaWG}, zusammen mit Jugend~hackt, eine Assembly mit eigenem Dom.
```

2020-03-10 16:05 UTC, rugk commented on chaosjetzt.tex
> +uns in kleineren und größeren Gruppen über verschiedene Themen ausgetauscht. Da es das erste Treffen war ging es inhaltlich mehr um Meta-Themen,
```suggestion
uns in kleineren und größeren Gruppen über verschiedene Themen ausgetauscht. Da es das erste Treffen war, ging es inhaltlich mehr um Meta-Themen,
```

2020-03-10 16:05 UTC, rugk commented on chaosjetzt.tex
> +Wenn ihr mitmachen wollt und/oder Infos zu uns, unserem Matrix-Server und unseren Events haben wollt guckt mal unter \url{https://chaos.jetzt/}.
```suggestion
Wenn ihr mitmachen wollt und/oder Infos zu uns, unserem Matrix-Server und unseren Events haben wollt, schaut mal unter \url{https://chaos.jetzt/}.
```

(less informal)

2020-03-10 16:05 UTC, rugk commented on chaosjetzt.tex
> +Ende Februar 2020 hat dann unser erstes, selbstorganisierten Geekend stattgefunden. Wir waren in Göttingen im Neotopia zu Gast und haben
```suggestion
Ende Februar 2020 hat unser erstes, selbstorganisierten Geekend stattgefunden. Wir waren in Göttingen im Neotopia zu Gast und haben 
```

-Füllwort

2020-03-10 20:45 UTC, raketenlurch commented
Ebenfalls done. :D

2020-03-10 21:27 UTC, merged